# main.yml
name: deploy to aliyun
# 触发方式
on: 
  push: # 触发动作
    branches:
      # 触发分支
      - main 
# 任务
jobs:
  # 第一个任务 build
  build:
    # 选择虚拟机
    runs-on: self-hosted
    # 步骤
    steps:
      # 使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      # npm install
      - name: npm install and build
        run: |
          screen -r 614601.pts-1.njucs
          cd njucs/njucs
          echo -e ‘\003’	  
          gitbook install
          gitbook build
        env:
          CI: true
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
      - run: |
	  gitbook serve 
          echo -e '\001'
          echo -e 'd'
