# main.yml
name: deploy to huaweicloud
# 触发方式
on: 
  push: # 触发动作
    branches:
      # 触发分支
      - main 
  pull_request:


# 任务
jobs:
  # 第一个任务 build
  build:
    # 选择虚拟机
    runs-on: self-hosted
    # 步骤
    steps:     
      - name: checkout
        uses: actions/checkout@v3      

      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: install gitbook
        run: npm install -g gitbook-cli --registry=registry.npmmirror.com

      - name: install plugins
        run: gitbook install
      
      - name: build page
        run: gitbook build
